const PRODUCTS=[
{id:1,name:'Daily Multi 01',ar:'مالتي فيتامين يومي',cat:'daily',price:149,rating:4.9,reviews:184,badge:'الأكثر طلباً',tone:'light',dose:'2 كبسولة',servings:'30 حصة',key:'فيتامينات + معادن',desc:'تركيبة يومية تجريبية ضمن نموذج العرض، مصممة ببطاقة معلومات واضحة وتجربة شراء راقية.'},
{id:2,name:'D3 + K2',ar:'فيتامين D3 + K2',cat:'daily',price:119,rating:4.8,reviews:96,badge:'روتين يومي',tone:'',dose:'1 كبسولة',servings:'60 حصة',key:'D3 + K2',desc:'منتج تجريبي لعرض كيفية تقديم المكونات والجرعات والمعلومات الأساسية بصورة مختصرة.'},
{id:3,name:'Whey 24',ar:'بروتين واي 24',cat:'performance',price:219,rating:4.9,reviews:241,badge:'PERFORMANCE',tone:'',dose:'1 مكيال',servings:'30 حصة',key:'24g Protein',desc:'تصميم منتج رياضي تجريبي يبرز كمية البروتين والحصص مع إضافة سريعة للسلة.'},
{id:4,name:'Crea 5',ar:'كرياتين مونوهيدرات',cat:'performance',price:129,rating:4.8,reviews:151,badge:'5G CREATINE',tone:'blue',dose:'5 جم',servings:'60 حصة',key:'Creatine Mono',desc:'نموذج لمنتج أحادي المكوّن بمعلومات مباشرة وتجربة شراء مناسبة لمنتجات الأداء الرياضي.'},
{id:5,name:'Hydra',ar:'إلكترولايتس هيدرا',cat:'energy',price:109,rating:4.7,reviews:77,badge:'ZERO SUGAR',tone:'green',dose:'1 ظرف',servings:'20 حصة',key:'Electrolytes',desc:'منتج تجريبي لفئة الترطيب والطاقة، بواجهة تساعد العميل على فهم الاستخدام والحصص سريعاً.'},
{id:6,name:'B12 Active',ar:'فيتامين B12 أكتف',cat:'energy',price:89,rating:4.7,reviews:68,badge:'ENERGY',tone:'light',dose:'1 قرص',servings:'60 حصة',key:'B12',desc:'نموذج عرض لفئة الطاقة اليومية مع تنظيم بسيط للبيانات والسعر والتقييم.'},
{id:7,name:'Mag 03',ar:'ماغنيسيوم 03',cat:'sleep',price:139,rating:4.9,reviews:133,badge:'EVENING',tone:'blue',dose:'2 كبسولة',servings:'30 حصة',key:'Magnesium',desc:'نموذج لفئة الروتين المسائي، مع التأكيد أن هذا المحتوى تجريبي وليس توصية صحية شخصية.'},
{id:8,name:'Omega Pure',ar:'أوميغا بيور',cat:'daily',price:159,rating:4.8,reviews:112,badge:'DAILY',tone:'green',dose:'2 كبسولة',servings:'45 حصة',key:'Omega-3',desc:'منتج تجريبي يكمل مجموعة العافية اليومية ويعرض بنية صفحة منتج واضحة ومختصرة.'}
];
let cart=JSON.parse(localStorage.getItem('nuranCart')||'{}');let wishlist=JSON.parse(localStorage.getItem('nuranWish')||'[]');let activeFilter='all';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR',maximumFractionDigits:0}).format(n);
function bottle(p,extra=''){return `<div class="mini-bottle ${p.tone} ${extra}"><i>NŪRAN</i><b>${p.name.toUpperCase()}</b><small>${p.key.toUpperCase()}</small></div>`}
function renderProducts(){let list=[...PRODUCTS];if(activeFilter!=='all')list=list.filter(p=>p.cat===activeFilter);const sort=$('#sortSelect').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);$('#productGrid').innerHTML=list.length?list.map(p=>`<article class="product-card" data-id="${p.id}"><div class="product-art"><span class="badge">${p.badge}</span><button class="wish-btn ${wishlist.includes(p.id)?'active':''}" data-wish="${p.id}" aria-label="إضافة للمفضلة">${wishlist.includes(p.id)?'♥':'♡'}</button>${bottle(p)}</div><div class="product-info"><div class="product-meta"><span>${p.name}</span><span class="rating">★ ${p.rating} (${p.reviews})</span></div><h3>${p.ar}</h3><div class="price-row"><div><span class="price">${money(p.price)}</span></div><button class="quick-add" data-add="${p.id}">أضف للسلة +</button></div></div></article>`).join(''):`<div class="no-results">لا توجد منتجات في هذا التصنيف حالياً.</div>`}
function persist(){localStorage.setItem('nuranCart',JSON.stringify(cart));localStorage.setItem('nuranWish',JSON.stringify(wishlist));updateCounts()}
function updateCounts(){const c=Object.values(cart).reduce((a,b)=>a+b,0);$('#cartCount').textContent=c;$('#wishCount').textContent=wishlist.length}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function addCart(id,q=1){cart[id]=(cart[id]||0)+q;persist();renderCart();toast('تمت الإضافة إلى السلة')}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];persist();renderProducts();toast(wishlist.includes(id)?'تمت الإضافة للمفضلة':'تمت الإزالة من المفضلة')}
function renderCart(){const entries=Object.entries(cart).filter(([,q])=>q>0);if(!entries.length){$('#cartItems').innerHTML='<div class="empty">سلتك فارغة.<br>ابدأ باختيار منتجاتك من المجموعة.</div>';$('#cartTotal').textContent=money(0);return}let total=0;$('#cartItems').innerHTML=entries.map(([id,q])=>{const p=PRODUCTS.find(x=>x.id==id);total+=p.price*q;return `<div class="cart-item"><div class="cart-thumb">${bottle(p)}</div><div><h4>${p.ar}</h4><small>${money(p.price)}</small><div class="cart-qty"><button data-dec="${p.id}">−</button><span>${q}</span><button data-inc="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">×</button></div>`}).join('');$('#cartTotal').textContent=money(total)}
function openCart(){renderCart();$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');$('#backdrop').classList.add('show')}
function closeDrawers(){$('#cartDrawer').classList.remove('open');$('#mobileMenu').classList.remove('open');$('#backdrop').classList.remove('show')}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);$('#modalCard').innerHTML=`<button class="icon-btn modal-close" data-close-modal>×</button><div class="modal-art">${bottle(p)}</div><div class="modal-copy"><span class="eyebrow dark">${p.badge}</span><h2>${p.ar}</h2><div class="rating">★★★★★ &nbsp; ${p.rating} · ${p.reviews} تقييم تجريبي</div><p>${p.desc}</p><div class="facts"><div><span>الجرعة المقترحة على العبوة</span><b>${p.dose}</b></div><div><span>عدد الحصص</span><b>${p.servings}</b></div><div><span>المكوّن الرئيسي</span><b>${p.key}</b></div></div><div class="price-row"><strong style="font-size:25px">${money(p.price)}</strong><button class="btn btn-dark" data-modal-add="${p.id}">أضف للسلة</button></div><p style="font-size:9px;margin-top:22px">هذا نموذج متجر تجريبي؛ المعلومات ليست بديلاً عن استشارة الطبيب أو الصيدلي، خاصة للحامل أو المرضع أو مستخدمي الأدوية أو أصحاب الحالات الصحية.</p></div>`;$('#productModal').classList.add('open');$('#productModal').setAttribute('aria-hidden','false')}
function closeModal(){$('#productModal').classList.remove('open');$('#productModal').setAttribute('aria-hidden','true')}
function openSearch(){$('#searchPanel').classList.add('open');$('#searchPanel').setAttribute('aria-hidden','false');setTimeout(()=>$('#searchInput').focus(),100);search('')}
function search(v){const term=v.trim().toLowerCase();let list=term?PRODUCTS.filter(p=>`${p.name} ${p.ar} ${p.key}`.toLowerCase().includes(term)):PRODUCTS.slice(0,4);$('#searchResults').innerHTML=list.map(p=>`<button class="search-result" style="width:100%;border-left:0;border-right:0;border-top:0;background:none;text-align:right" data-search-product="${p.id}"><span>${p.ar}<small style="display:block;color:#999">${p.name}</small></span><b>${money(p.price)}</b></button>`).join('')||'<div class="empty">لا توجد نتائج مطابقة.</div>'}

document.addEventListener('click',e=>{const t=e.target.closest('button,[data-id]');if(!t)return;if(t.dataset.add)addCart(+t.dataset.add);else if(t.dataset.wish)toggleWish(+t.dataset.wish);else if(t.dataset.id&&!e.target.closest('[data-add],[data-wish]'))openProduct(+t.dataset.id);else if(t.dataset.inc){cart[t.dataset.inc]=(cart[t.dataset.inc]||0)+1;persist();renderCart()}else if(t.dataset.dec){cart[t.dataset.dec]=Math.max(0,(cart[t.dataset.dec]||0)-1);if(!cart[t.dataset.dec])delete cart[t.dataset.dec];persist();renderCart()}else if(t.dataset.remove){delete cart[t.dataset.remove];persist();renderCart()}else if(t.dataset.modalAdd){addCart(+t.dataset.modalAdd);closeModal();openCart()}else if(t.dataset.closeModal!==undefined)closeModal();else if(t.dataset.closeCart!==undefined||t.dataset.closeMenu!==undefined)closeDrawers();else if(t.dataset.searchProduct){$('#searchPanel').classList.remove('open');openProduct(+t.dataset.searchProduct)}});
$('#cartBtn').addEventListener('click',openCart);$('#menuBtn').addEventListener('click',()=>{$('#mobileMenu').classList.add('open');$('#backdrop').classList.add('show')});$('#backdrop').addEventListener('click',closeDrawers);$('#searchBtn').addEventListener('click',openSearch);$('[data-close-search]').addEventListener('click',()=>$('#searchPanel').classList.remove('open'));$('#searchPanel').addEventListener('click',e=>{if(e.target===$('#searchPanel'))$('#searchPanel').classList.remove('open')});$('#productModal').addEventListener('click',e=>{if(e.target===$('#productModal'))closeModal()});$('#searchInput').addEventListener('input',e=>search(e.target.value));
$$('.chip').forEach(b=>b.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderProducts()}));$('#sortSelect').addEventListener('change',renderProducts);$$('.goal-card').forEach(g=>g.addEventListener('click',()=>{activeFilter=g.dataset.category;$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderProducts();$('#shop').scrollIntoView({behavior:'smooth'})}));
$('#bundleAdd').addEventListener('click',()=>{addCart(3);addCart(4);addCart(5);toast('أضفنا منتجات الباقة إلى السلة')});$('#checkoutBtn').addEventListener('click',()=>toast('الدفع غير مفعّل في نموذج العرض'));
$('#wishlistBtn').addEventListener('click',()=>{if(!wishlist.length){toast('المفضلة فارغة حالياً');return}activeFilter='all';renderProducts();$('#shop').scrollIntoView({behavior:'smooth'});toast(`${wishlist.length} منتج في المفضلة`)});
$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();e.target.reset();toast('تم تسجيل الاشتراك التجريبي')});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawers();closeModal();$('#searchPanel').classList.remove('open')}});
renderProducts();renderCart();updateCounts();
