const STORE={shippingFee:25,freeShippingAt:299};
const CATEGORIES=[
{id:'all',ar:'الكل',en:'ALL',color:'#171714'},{id:'protein',ar:'البروتين',en:'PROTEIN',color:'#d1a34d'},{id:'creatine',ar:'الكرياتين',en:'CREATINE',color:'#4f83c2'},{id:'preworkout',ar:'قبل التمرين',en:'PRE-WORKOUT',color:'#d58248'},{id:'vitamins',ar:'الفيتامينات',en:'VITAMINS',color:'#c8b17a'},{id:'minerals',ar:'المعادن',en:'MINERALS',color:'#735a98'},{id:'omega',ar:'أوميغا',en:'OMEGA',color:'#3f738b'},{id:'immunity',ar:'المناعة',en:'IMMUNITY',color:'#6e9d74'},{id:'sleep',ar:'النوم والاسترخاء',en:'SLEEP',color:'#67508d'},{id:'hydration',ar:'الترطيب',en:'HYDRATION',color:'#4a9a91'},{id:'joints',ar:'المفاصل والكولاجين',en:'JOINTS',color:'#9c5b53'}];
const PRODUCTS=[
[1,'protein','واي بروتين 24 — شوكولاتة','WHEY 24 CHOCOLATE',219,249,4.9,318,'BESTSELLER','tub','900G','30 حصة','24g Protein','#d1a34d'],
[2,'protein','واي بروتين 24 — فانيلا','WHEY 24 VANILLA',219,null,4.8,204,'POPULAR','tub','900G','30 حصة','24g Protein','#d9be83'],
[3,'protein','آيزوليت 27','ISOLATE 27',279,309,4.9,176,'LEAN','tub','850G','28 حصة','27g Protein','#b38a42'],
[4,'protein','كازين نايت','CASEIN NIGHT',239,null,4.7,89,'NIGHT','tub','900G','30 حصة','Slow Protein','#8b6b8d'],
[5,'creatine','كرياتين مونوهيدرات 5','CREA 5',129,null,4.9,402,'5G','jar','300G','60 حصة','Creatine Mono','#4f83c2'],
[6,'creatine','كرياتين ميكرونايزد','CREA MICRO',149,169,4.8,187,'MICRO','jar','300G','60 حصة','Micronized','#3d6fae'],
[7,'creatine','كرياتين + إلكترولايتس','CREA HYDRA',159,null,4.7,74,'HYBRID','jar','360G','30 حصة','Creatine + Electrolytes','#478fa3'],
[8,'creatine','كرياتين كبسولات','CREA CAPS',119,null,4.6,61,'CAPS','jar','120 CAPS','30 حصة','Creatine','#5b79ad'],
[9,'preworkout','بري ووركاوت فلو','FLOW PRE',169,189,4.8,226,'ENERGY','jar','300G','30 حصة','Pre-Workout','#d58248'],
[10,'preworkout','بري ووركاوت زيرو','ZERO PRE',159,null,4.7,142,'ZERO SUGAR','jar','270G','30 حصة','Zero Sugar','#cc6e42'],
[11,'preworkout','سيترولين 6','CITRA 6',139,null,4.8,111,'PUMP','jar','240G','40 حصة','Citrulline','#db7e51'],
[12,'preworkout','بيتا ألانين','BETA 3.2',119,null,4.6,73,'ENDURANCE','jar','250G','75 حصة','Beta Alanine','#bd6844'],
[13,'vitamins','مالتي فيتامين يومي','DAILY MULTI 01',149,169,4.9,278,'DAILY','jar','60 CAPS','30 حصة','Vitamins + Minerals','#c8b17a',true],
[14,'vitamins','فيتامين D3 + K2','D3 + K2',119,null,4.9,241,'ESSENTIAL','jar','60 CAPS','60 حصة','D3 + K2','#d5bd7c',true],
[15,'vitamins','فيتامين B12 أكتف','B12 ACTIVE',89,null,4.7,134,'B12','jar','60 TABS','60 حصة','Vitamin B12','#d58248',true],
[16,'vitamins','فيتامين C 1000','C 1000',79,89,4.8,193,'1000MG','jar','60 TABS','60 حصة','Vitamin C','#d8a04b',true],
[17,'minerals','ماغنيسيوم 03','MAG 03',139,null,4.9,297,'EVENING','jar','60 CAPS','30 حصة','Magnesium','#735a98'],
[18,'minerals','زنك 25','ZINC 25',69,null,4.7,122,'25MG','jar','90 TABS','90 حصة','Zinc','#80679f'],
[19,'minerals','كالسيوم + D','CAL + D',109,null,4.6,78,'BONES','jar','90 TABS','45 حصة','Calcium + D','#8d78aa',true],
[20,'minerals','حديد بلس','IRON PLUS',99,null,4.7,81,'IRON','jar','60 CAPS','60 حصة','Iron','#6d527f'],
[21,'omega','أوميغا 3 بيور','OMEGA PURE',159,179,4.9,264,'OMEGA-3','jar','90 SOFTGELS','45 حصة','EPA + DHA','#3f738b'],
[22,'omega','أوميغا 3 ألترا','OMEGA ULTRA',189,null,4.8,127,'HIGH EPA','jar','90 SOFTGELS','45 حصة','High EPA','#315f7b'],
[23,'omega','أوميغا نباتي','ALGAE OMEGA',179,null,4.7,66,'VEGAN','jar','60 SOFTGELS','30 حصة','Algae Oil','#4f8190',true],
[24,'omega','أوميغا 3 + D3','OMEGA + D3',169,null,4.8,93,'DUO','jar','60 SOFTGELS','30 حصة','Omega + D3','#47708e'],
[25,'immunity','إميون ديلي','IMMUNE DAILY',139,159,4.8,171,'IMMUNITY','jar','60 CAPS','30 حصة','C + D + Zinc','#6e9d74',true],
[26,'immunity','إلدر بيري + C','ELDER + C',129,null,4.7,88,'BERRY','jar','60 GUMMIES','30 حصة','Elderberry','#6c8564'],
[27,'immunity','كويرسيتين بلس','QUER PLUS',149,null,4.6,54,'PLUS','jar','60 CAPS','30 حصة','Quercetin','#7ba17a',true],
[28,'immunity','بروبيوتك 20','PROBIO 20',169,189,4.8,139,'20B CFU','jar','30 CAPS','30 حصة','Probiotic','#5d8a72',true],
[29,'sleep','سليب ماغ','SLEEP MAG',149,null,4.9,213,'NIGHT','jar','60 CAPS','30 حصة','Magnesium Blend','#67508d'],
[30,'sleep','ميلاتونين 3','MELA 3',89,null,4.7,157,'3MG','jar','60 TABS','60 حصة','Melatonin','#5e477f'],
[31,'sleep','إل ثيانين','L-THEANINE',119,null,4.8,91,'CALM','jar','60 CAPS','60 حصة','L-Theanine','#7b6298',true],
[32,'sleep','نايت روتين','NIGHT ROUTINE',159,179,4.8,116,'BLEND','jar','60 CAPS','30 حصة','Night Blend','#574373'],
[33,'hydration','هيدرا زيرو','HYDRA ZERO',109,129,4.8,187,'ZERO SUGAR','jar','20 SERV','20 حصة','Electrolytes','#4a9a91',true],
[34,'hydration','هيدرا ليمون','HYDRA LEMON',109,null,4.7,102,'LEMON','jar','20 SERV','20 حصة','Electrolytes','#72a873',true],
[35,'hydration','هيدرا بيري','HYDRA BERRY',109,null,4.7,94,'BERRY','jar','20 SERV','20 حصة','Electrolytes','#6b8f92'],
[36,'hydration','أمينو هيدرا','AMINO HYDRA',149,169,4.8,121,'AMINO','jar','360G','30 حصة','Amino + Electrolytes','#3e8784'],
[37,'joints','كولاجين ببتايدز','COLLAGEN PEPTIDES',169,189,4.8,164,'COLLAGEN','tub','450G','30 حصة','Collagen Peptides','#9c5b53',true],
[38,'joints','جوينت كومبلكس','JOINT COMPLEX',149,null,4.7,96,'JOINTS','jar','90 CAPS','30 حصة','Joint Blend','#8a5d54'],
[39,'joints','جلوكوزامين + MSM','GLUCO + MSM',139,null,4.7,102,'MSM','jar','90 TABS','30 حصة','Glucosamine + MSM','#a36758',true],
[40,'joints','كركمين أكتف','CURCUMIN ACTIVE',129,149,4.8,118,'CURCUMIN','jar','60 CAPS','30 حصة','Curcumin','#a4794f',true]
].map(x=>({id:x[0],cat:x[1],ar:x[2],en:x[3],price:x[4],old:x[5],rating:x[6],reviews:x[7],badge:x[8],type:x[9],size:x[10],servings:x[11],key:x[12],color:x[13],light:!!x[14],desc:`${x[2]} ضمن مجموعة NŪRAN ${CATEGORIES.find(c=>c.id===x[1])?.ar||''}، بمعلومات عبوة واضحة وتصميم موحّد.`}));
const BUNDLES=[{id:'performance',title:'باقة الأداء',subtitle:'PERFORMANCE ROUTINE',ids:[1,5,33],price:399},{id:'daily',title:'باقة الأساس اليومي',subtitle:'DAILY ESSENTIALS',ids:[13,14,21],price:369},{id:'evening',title:'باقة الروتين المسائي',subtitle:'EVENING ROUTINE',ids:[17,29,31],price:329}];
let cart=safe('nuranCart3',{}),wishlist=safe('nuranWish3',[]),active='all';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR',maximumFractionDigits:0}).format(n);
function safe(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function pack(p){const cls=p.type==='tub'?'tub':'jar';return `<div class="packshot"><div class="${cls} ${p.light?'light':''}" style="--accent:${p.color}"><i>NŪRAN</i><strong>${p.en.split(' ').slice(0,2).join(' ')}</strong><small>${CATEGORIES.find(c=>c.id===p.cat)?.en||''}</small><span>${p.size}</span></div></div>`}
function persist(){localStorage.setItem('nuranCart3',JSON.stringify(cart));localStorage.setItem('nuranWish3',JSON.stringify(wishlist));counts()}
function counts(){$('#cartCount').textContent=Object.values(cart).reduce((a,b)=>a+b,0);$('#wishCount').textContent=wishlist.length}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>t.classList.remove('show'),1800)}
function card(p){return `<article class="product-card" data-id="${p.id}"><div class="product-stage" style="--accent:${p.color}"><span class="product-badge">${p.badge}</span><button class="wish ${wishlist.includes(p.id)?'active':''}" data-wish="${p.id}">${wishlist.includes(p.id)?'♥':'♡'}</button>${pack(p)}</div><div class="product-info"><div class="product-meta"><span>${p.key}</span><span>${p.servings}</span></div><h3>${p.ar}</h3><div class="en">${p.en}</div><div class="rating">★★★★★ <span>${p.rating} · ${p.reviews}</span></div><div class="price-row"><div><span class="price">${money(p.price)}</span>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><button class="add-btn" data-add="${p.id}">أضف للسلة +</button></div></div></article>`}
function renderCategories(){$('#categoryGrid').innerHTML=CATEGORIES.slice(1).map(c=>`<button class="category-card" data-cat="${c.id}" style="--accent:${c.color}"><div class="category-swatch"></div><small>${c.en}</small><b>${c.ar}</b><span>4 منتجات</span></button>`).join('')}
function renderFilters(){$('#filterChips').innerHTML=CATEGORIES.map(c=>`<button class="chip ${c.id===active?'active':''}" data-filter="${c.id}">${c.ar}</button>`).join('')}
function renderFeatured(){$('#featuredGrid').innerHTML=PRODUCTS.filter(p=>[1,5,13,21,29,33,37,3].includes(p.id)).map(card).join('')}
function renderProducts(){let list=active==='all'?[...PRODUCTS]:PRODUCTS.filter(p=>p.cat===active);const s=$('#sortSelect').value;if(s==='low')list.sort((a,b)=>a.price-b.price);if(s==='high')list.sort((a,b)=>b.price-a.price);if(s==='rating')list.sort((a,b)=>b.rating-a.rating);$('#resultCount').textContent=`${list.length} منتج`;$('#productGrid').innerHTML=list.map(card).join('');renderFilters()}
function renderBundles(){$('#bundleGrid').innerHTML=BUNDLES.map(b=>{const ps=b.ids.map(id=>PRODUCTS.find(p=>p.id===id));return `<article class="bundle-card"><div class="bundle-art">${ps.map(pack).join('')}</div><div class="bundle-info"><small>${b.subtitle}</small><h3>${b.title}</h3><p>${ps.map(p=>p.ar).join(' + ')}</p><div class="bundle-price"><strong>${money(b.price)}</strong><button data-bundle="${b.id}">أضف الباقة +</button></div></div></article>`}).join('')}
function add(id,q=1){cart[id]=(cart[id]||0)+q;persist();renderCart();toast('تمت الإضافة إلى السلة')}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];persist();renderProducts();renderFeatured();toast(wishlist.includes(id)?'تم الحفظ في المفضلة':'تمت الإزالة من المفضلة')}
function totals(){let subtotal=0;Object.entries(cart).forEach(([id,q])=>{const p=PRODUCTS.find(x=>x.id==id);if(p)subtotal+=p.price*q});const shipping=subtotal===0?0:subtotal>=STORE.freeShippingAt?0:STORE.shippingFee;return{subtotal,shipping,total:subtotal+shipping}}
function renderCart(){const entries=Object.entries(cart).filter(([,q])=>q>0);if(!entries.length){$('#cartItems').innerHTML='<div class="empty">سلتك فارغة.<br>ابدأ باختيار منتجاتك من المجموعة.</div>';$('#cartSubtotal').textContent=money(0);$('#shippingNote').textContent='';return}$('#cartItems').innerHTML=entries.map(([id,q])=>{const p=PRODUCTS.find(x=>x.id==id);return `<div class="cart-item"><div class="cart-thumb">${pack(p)}</div><div><h4>${p.ar}</h4><small>${money(p.price)}</small><div class="qty"><button data-dec="${p.id}">−</button><span>${q}</span><button data-inc="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">×</button></div>`}).join('');const t=totals();$('#cartSubtotal').textContent=money(t.subtotal);$('#shippingNote').textContent=t.shipping===0?'الشحن مجاني لهذا الطلب':`أضف ${money(STORE.freeShippingAt-t.subtotal)} للحصول على شحن مجاني`}
function lock(v){document.body.classList.toggle('lock',v)}
function openCart(){renderCart();$('#cartDrawer').classList.add('open');$('#backdrop').classList.add('show');lock(true)}
function closeDrawers(){$('#cartDrawer').classList.remove('open');$('#mobileMenu').classList.remove('open');$('#backdrop').classList.remove('show');lock(false)}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);$('#productModalCard').innerHTML=`<button class="modal-close" data-close-product>×</button><div class="modal-art" style="--accent:${p.color}">${pack(p)}</div><div class="modal-copy"><span class="eyebrow dark">${p.badge}</span><h2>${p.ar}</h2><div class="modal-en">${p.en}</div><div class="rating">★★★★★ <span>${p.rating} · ${p.reviews} تقييم</span></div><p>${p.desc}</p><div class="facts"><div><span>العبوة</span><b>${p.size}</b></div><div><span>عدد الحصص</span><b>${p.servings}</b></div><div><span>التركيبة</span><b>${p.key}</b></div></div><div class="price-row"><strong class="price">${money(p.price)}</strong><button class="btn dark" data-modal-add="${p.id}">أضف للسلة +</button></div></div>`;$('#productModal').classList.add('open');lock(true)}
function closeProduct(){$('#productModal').classList.remove('open');lock(false)}
function openSearch(){$('#searchPanel').classList.add('open');lock(true);setTimeout(()=>$('#searchInput').focus(),80);doSearch('')}
function closeSearch(){$('#searchPanel').classList.remove('open');lock(false)}
function doSearch(v){const t=v.trim().toLowerCase(),list=t?PRODUCTS.filter(p=>`${p.ar} ${p.en} ${p.key}`.toLowerCase().includes(t)):PRODUCTS.slice(0,6);$('#searchResults').innerHTML=list.map(p=>`<button class="search-result" data-search-id="${p.id}"><div style="height:50px;overflow:hidden">${pack(p)}</div><span><strong>${p.ar}</strong><small>${p.en}</small></span><b>${money(p.price)}</b></button>`).join('')||'<div class="empty">لا توجد نتائج مطابقة.</div>'}
function applyCat(cat){active=cat;renderProducts();$('#shop').scrollIntoView({behavior:'smooth'})}
function checkoutSummary(){const t=totals();$('#checkoutSummary').innerHTML=`<div><span>المنتجات</span><b>${money(t.subtotal)}</b></div><div><span>الشحن</span><b>${t.shipping?money(t.shipping):'مجاني'}</b></div><div><strong>الإجمالي</strong><strong>${money(t.total)}</strong></div>`}
function openCheckout(){if(!Object.keys(cart).length)return toast('أضف منتجات للسلة أولًا');closeDrawers();checkoutSummary();$('#checkoutModal').classList.add('open');lock(true)}
function closeCheckout(){$('#checkoutModal').classList.remove('open');lock(false)}
document.addEventListener('click',e=>{const t=e.target.closest('button,[data-id]');if(!t)return;if(t.dataset.add)add(+t.dataset.add);else if(t.dataset.wish)toggleWish(+t.dataset.wish);else if(t.dataset.id&&!e.target.closest('[data-add],[data-wish]'))openProduct(+t.dataset.id);else if(t.dataset.cat)applyCat(t.dataset.cat);else if(t.dataset.filter!==undefined){active=t.dataset.filter;renderProducts()}else if(t.dataset.inc){cart[t.dataset.inc]=(cart[t.dataset.inc]||0)+1;persist();renderCart()}else if(t.dataset.dec){cart[t.dataset.dec]=Math.max(0,(cart[t.dataset.dec]||0)-1);if(!cart[t.dataset.dec])delete cart[t.dataset.dec];persist();renderCart()}else if(t.dataset.remove){delete cart[t.dataset.remove];persist();renderCart()}else if(t.dataset.modalAdd){add(+t.dataset.modalAdd);closeProduct();setTimeout(openCart,80)}else if(t.dataset.closeProduct!==undefined)closeProduct();else if(t.dataset.closeCart!==undefined||t.dataset.closeMenu!==undefined)closeDrawers();else if(t.dataset.closeSearch!==undefined)closeSearch();else if(t.dataset.closeCheckout!==undefined)closeCheckout();else if(t.dataset.searchId){closeSearch();setTimeout(()=>openProduct(+t.dataset.searchId),60)}else if(t.dataset.bundle){const b=BUNDLES.find(x=>x.id===t.dataset.bundle);b.ids.forEach(id=>cart[id]=(cart[id]||0)+1);persist();renderCart();toast('تمت إضافة الباقة للسلة')}})
$('#cartBtn').addEventListener('click',openCart);$('#menuBtn').addEventListener('click',()=>{$('#mobileMenu').classList.add('open');$('#backdrop').classList.add('show');lock(true)});$('#backdrop').addEventListener('click',closeDrawers);$('#searchBtn').addEventListener('click',openSearch);$('#searchInput').addEventListener('input',e=>doSearch(e.target.value));$('#sortSelect').addEventListener('change',renderProducts);$('#checkoutBtn').addEventListener('click',openCheckout);$('#wishBtn').addEventListener('click',()=>{if(!wishlist.length)return toast('المفضلة فارغة');active='all';renderProducts();$('#shop').scrollIntoView({behavior:'smooth'});toast(`${wishlist.length} منتج محفوظ`)});
$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();e.target.reset();toast('تم تسجيل الاشتراك')});
$('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();toast('اربط بيانات التاجر وBackend الطلبات لتفعيل الإرسال الفعلي')});
$('#productModal').addEventListener('click',e=>{if(e.target===$('#productModal'))closeProduct()});$('#searchPanel').addEventListener('click',e=>{if(e.target===$('#searchPanel'))closeSearch()});$('#checkoutModal').addEventListener('click',e=>{if(e.target===$('#checkoutModal'))closeCheckout()});$$('.mobile-menu a').forEach(a=>a.addEventListener('click',closeDrawers));window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawers();closeProduct();closeSearch();closeCheckout()}});
const video=$('#heroVideo');$('#videoControl').addEventListener('click',()=>{video.paused?video.play():video.pause();$('#videoLabel').textContent=video.paused?'تشغيل الحركة':'إيقاف الحركة'});
renderCategories();renderFilters();renderFeatured();renderProducts();renderBundles();renderCart();counts();